### ISSUE TITLE
What should be various defined access levels?

### ISSUE THREAD

**Issue by DhaliwalX** [csspec/auth-portal#4]
For now, I have defined ADMIN with access level of 1 (on scale of 1-10) and UNKNOWN user with 10.
What about students, teachers, Society heads, CR's etc?

**Comment by kvibhore** [comment]
I think the concept of tags might prove better as some specific tags can be attached to a person in case he has access to that level. For example, if a person has authority to give permit for Audi booking, a tag can be added for the same in his info. 
Another drawback of access levels can be in a scenario where u introduce a new access and only some persona from one access level are to be given access. The access level would have to be divided in this case but simply adding one tag will work better.

**Comment by akshayarora2009** [comment]
I suggest a scheme that has a lot of room for new roles to be added in the future. This is because we might miss some roles during the development stage. 

High-level view:
(Lower number means higher access level)

```
Level(s)  |  Role Name      |  Role Description
--------------------------------------------------
1         |  Super User     | Access to all services' dashboard
2         |  Service admin  | Full access to a particular service
3 - 13    | Staff & Teachers | Varying level of staff and teachers (some can be left blank)-
14-19    | Students | Varying level of students' privileges^^
```

^^ - Currently we might have 3 roles of students: 
13 - Club Gen. Secretary & Secretary
18 - CR
19 - normal student

14, 15, 16, 17 to be left blank so that any other role can be accommodated in the future.

Similar schema can be followed for Staff & teachers as well. 

**Range of values can be changed as well.**

**Comment by akshayarora2009** [comment]
@kvibhore I think, adding tags is too cumbersome and repetitive. Doing such tagging will result in a tight coupling between a person and the privileges he has, rather than the role and the privileges associated.

**Comment by kvibhore** [comment]
We can make use of both, with keeping less number of access levels but maintaining tags for the special privileges if someone has. The basic behaviors can be checked directly using the access the access level and special privilege using tags. This will keep it more generic and scalable.

**Comment by DhaliwalX** [comment]
Both seems legit. But for now I have added roles based on the range. Please check the Pull request #3 .

**Comment by DhaliwalX** [comment]
Also I am following the web flow based on GitHub API.
Actually I have considered two web flows. One for trusted services and other for untrusted third party services. Untrusted one follows web flow based on GitHub API. They are first provided `code` which when they send back with their `client_secret` and then they can receive `access_token`. See https://github.com/PrinceDhaliwal/auth-portal/blob/master/Docs/Webflow.md for more details.

**Comment by akshayarora2009** [comment]
@PrinceDhaliwal I have a question regarding the Web flow you have written:

In first point, you are giving the client the option of providing two optional parameters: `services` and `redirect_uri`. 

**Are these mutually exclusive?** 

Because `services` argument shall be provided by only our own services, and will be server to server calls.
So I suggest, **please create a new endpoint for calls that require service-to-service authorization.** 

These two endpoints (one for service authorization, and one for client authorization) will have mandatory arguments `services` and `redirect_uri`.

What do you think?

**Comment by akshayarora2009** [comment]
@PrinceDhaliwal Also, One question regarding the second point as well. 

You write

> Authorization Portal sends code to the redirect_uri parameter.

But as far as OAuth is concerned, you should be sending the access token directly when a web browser is making a call (the scenario with `redirect_uri`). 

Shouldn't the Auth Code step not present in this case?

(More details here: http://stackoverflow.com/questions/13387698/why-is-there-an-authorization-code-flow-in-oauth2-when-implicit-flow-works-s)

**Comment by DhaliwalX** [comment]
Sir, if we send the `access_token` directly, then there will be security issues. Consider a person(hacker) using the feedback-portal. So as usual he will go to the feedback.pec.ac.in and on seeing that feedback.pec.ac.in  will receive the `access_token`, he starts intercepting the request on which `access_token` will arrive. He reads the `access_token` and starts using that `access_token` for retrieving information from the identity server which we don't want.

Problem is that auth-server doesn't know from where the request is coming, whether it is feedback-portal or hacker requesting.

Another problem is that not all services are [browser based](https://aaronparecki.com/2012/07/29/2/oauth2-simplified#authorization). See [this](https://tools.ietf.org/html/rfc6749#section-1.3)

Regarding,

> **create a new endpoint for calls that require service-to-service authorization**

I am working on it and will push it by evening.

**Comment by DhaliwalX** [comment]
> **Are these mutually exclusive?**

I am assuming when services will "register" themselves then they have to tell which services they will be using and what will be their `redirect_uri` etc. So `redirect_uri` and `services` will default to their registered values.

So clients have an option of having `access_token` corresponding to less services demanded in `services` parameter (They can access more services than they are registered for).

**Comment by akshayarora2009** [comment]
>  he starts intercepting the request on which access_token will arrive

How can he intercept the request as we are gonna be using HTTPS. (SSL-enabled)?

**Comment by akshayarora2009** [comment]
> Problem is that auth-server doesn't know from where the request is coming, whether it is feedback-portal or hacker requesting.

This is correct. Auth-server _shouldn't_ actually know from where the request is coming. We should be able to make our token distribution secure enough.

> Another problem is that not all services are browser based.

Correct. But I will again emphasize that sending a `code` for browser-based apps adds no extra protection over sending the `token` if the connection is HTTPS. 

You know when the `code` is useful? When the client sends his `id` and `secret` along with `code` to request a `token`. For browser based apps, we cannot send `secret` to the auth-server. 

Please give this a thought, and let me know if you have any doubts.

**Comment by DhaliwalX** [comment]
So I have to just issue the `access_token` to the client?

If yes, then validity of the `access_token` should be very small, Right?

**Comment by DhaliwalX** [comment]
About the hash fragments,
Do I have to pass the `access_token` via hash fragment? Like,

```
    www.example.com/something#Afsnir3kjn43
```

Right?

**Comment by akshayarora2009** [comment]
Yes and Yes.

Summarizing what is to be done.
1. If the `token` is being set by Auth portal's own frontend **in the browser**, directly return the token as a hash fragment to the `redirect_uri`. This token can be stored in cookies, and should have small validity time.
2. If a backend server (some of our service) is asking for a `token`, then you can follow the approach that involves first sending a `code`, and then returning `token` after client sends the `code` along with `client_id` and `client_secret`.

Point 2 will make sure that only the Auth server will need to install SSL and not **necessarily** the other services.

I hope this clears your doubt.

**Comment by DhaliwalX** [comment]
Yes thank you

**Comment by DhaliwalX** [comment]
Then should I include an extra argument for `/oauth/authorize` which will specify the type of token the client wants to access. In terms of OAuth 2.0, `authorization_code` will be one and other will be `implicit`. So extra parameter will be `grant_type` whose value will be one of `authorization_code` and `implicit`.

Am I going right?

**Comment by akshayarora2009** [comment]
You are right. I suggest you keep a parameter named `response_type` which accepts either `code` or `token`. ( I feel this naming feels better :smile: )

For security reasons, if someone asks you for `token` directly, make sure that:
1. `redirect_uri` mentioned in the request is registered with the Auth portal and valid.
2.  Pass token as a hash fragment.
