### ISSUE TITLE
How services will register themselves to auth-portal? 

### ISSUE THREAD

**Issue by DhaliwalX** [csspec/auth-portal#5]
Currently I have not written code for registration of services. We can't hard code them into the database. Instead there should be a registration portal where new services can request themselves and admin can approve or disapprove requests. Or there should be a portal for admin, where he can add new service to the database.

**Comment by akshayarora2009** [comment]
I don't see any reason why we don't hardcode them. In our first phase of development, we will be having a maximum of 8-10 services. This won't be much difficult to handle.

Creating a separate portal is a big overhead. We should only focus on our main product right now. We can think about it later.

**Comment by DhaliwalX** [comment]
I am not recommending of creating a separate portal. It will be a part of Authorization portal. Database about services will be managed by it.

**Comment by DhaliwalX** [comment]
I am keeping database of client's (services). I have kept the database about the services which a client can also. 

By portal, I meant a UI (website) for admin :sweat_smile: .

**Comment by kvibhore** [comment]
I would say hardcoding is sufficient for now, we will make it dynamic later when we have some proper time to perform testing and everything for this, including that of UI part.
